REVOKE CONNECT ON DATABASE report_test FROM PUBLIC;
REVOKE USAGE, CREATE ON SCHEMA public FROM PUBLIC;

CREATE SCHEMA IF NOT EXISTS report_label;
REVOKE CREATE ON SCHEMA report_label FROM PUBLIC;

-- migration user
CREATE ROLE migration_user NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN PASSWORD 'test';
GRANT CONNECT ON DATABASE report_test TO migration_user;
GRANT USAGE, CREATE ON SCHEMA report_label TO migration_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA report_label GRANT ALL PRIVILEGES ON TABLES TO migration_user;

-- web user
CREATE ROLE web_user NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN PASSWORD 'test';
GRANT CONNECT ON DATABASE report_test TO web_user;
GRANT USAGE ON SCHEMA report_label TO web_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA report_label TO web_user;
ALTER DEFAULT PRIVILEGES FOR USER migration_user IN SCHEMA report_label GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON TABLES TO web_user;
ALTER DEFAULT PRIVILEGES FOR USER migration_user IN SCHEMA report_label GRANT SELECT, USAGE ON SEQUENCES TO web_user;
